### ISSUE TITLE
Maintenance:  Update Palette class

### ISSUE THREAD

**Issue by sabadam32** [terrysimons/glitchygames#1]
Reorganize resources and add doc strings.

## Tasks

- [x] Move resources to the root of the source folder
- [x] Move palette files into `palette` subfolder
- [x] Update `ColorPalette` class to reference new location
- [x] Add Docstrings to current code
